export const ItemObj = [
  {
    title: "아기 신발 무료나눔해요",
    content:
      "200 운동화 아이가 발이 쑥쑥 커서 맞지 않아 나눔합니다 상태 나쁘지 않습니다 ",
    area: "서울시",
    timeAge: "1분전",
    img: ["shoes", "blouse"],
    main: "상의",
    sub: "티셔츠",
    id: 11111,
  },
  {
    title: "아기 신발 무료나눔해요",
    content:
      "200 운동화 아이가 발이 쑥쑥 커서 맞지 않아 나눔합니다 상태 나쁘지 않습니다 ",
    area: "서울시",
    timeAge: "1분전",
    img: ["shoes"],
    main: "상의",
    sub: "티셔츠",
    id: 11112,
  },
  {
    title: "아기 신발 무료나눔해요",
    content:
      "200 운동화 아이가 발이 쑥쑥 커서 맞지 않아 나눔합니다 상태 나쁘지 않습니다 ",
    area: "서울시",
    timeAge: "1분전",
    img: ["shoes"],
    main: "상의",
    sub: "티셔츠",
    id: 11113,
  },
  {
    title: "아기 신발 무료나눔해요",
    content:
      "200 운동화 아이가 발이 쑥쑥 커서 맞지 않아 나눔합니다 상태 나쁘지 않습니다 ",
    area: "서울시",
    timeAge: "1분전",
    img: ["shoes"],
    main: "상의",
    sub: "티셔츠",
    id: 11114,
  },
  {
    title: "아기 신발 무료나눔해요",
    content:
      "200 운동화 아이가 발이 쑥쑥 커서 맞지 않아 나눔합니다 상태 나쁘지 않습니다 ",
    area: "서울시",
    timeAge: "1분전",
    img: ["shoes"],
    main: "상의",
    sub: "티셔츠",
    id: 11115,
  },
  {
    title: "아기 신발 무료나눔해요",
    content:
      "200 운동화 아이가 발이 쑥쑥 커서 맞지 않아 나눔합니다 상태 나쁘지 않습니다 ",
    area: "서울시",
    timeAge: "1분전",
    img: ["shoes"],
    main: "상의",
    sub: "티셔츠",
    id: 11116,
  },
  {
    title: "아기 신발 무료나눔해요",
    content:
      "200 운동화 아이가 발이 쑥쑥 커서 맞지 않아 나눔합니다 상태 나쁘지 않습니다 ",
    area: "서울시",
    timeAge: "1분전",
    img: ["shoes"],
    main: "상의",
    sub: "티셔츠",
    id: 11117,
  },

  {
    title: "새 목걸이 가져가실 분",
    content: "선물 받았는데 취향에 맞지 않아 나눔해요",
    area: "인천시",
    timeAge: "2분전",
    img: ["necklace"],
    main: "상의",
    sub: "티셔츠",
    id: 11118,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["necklace"],
    main: "상의",
    sub: "블라우스",
    id: 11119,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["blouse"],
    main: "상의",
    sub: "블라우스",
    id: 11120,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["blouse"],
    main: "상의",
    sub: "블라우스",
    id: 11121,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["blouse"],
    main: "상의",
    sub: "블라우스",
    id: 11122,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["blouse"],
    main: "상의",
    sub: "블라우스",
    id: 11123,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["blouse"],
    main: "하의",
    sub: "청바지",
    id: 11124,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["blouse"],
    main: "하의",
    sub: "청바지",
    id: 11125,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["blouse"],
    main: "하의",
    sub: "청바지",
    id: 11126,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["blouse"],
    main: "하의",
    sub: "청바지",
    id: 11127,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["blouse"],
    main: "하의",
    sub: "기타",
    id: 11128,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["blouse"],
    main: "신발",
    sub: "운동화",
    id: 11129,
  },
  {
    title: "블라우스 나눔합니다!!",
    content: "거의 새거입니다~  ",
    area: "부산시",
    timeAge: "3분전",
    img: ["blouse"],
    main: "악세서리",
    sub: "목걸이",
    id: 11130,
  },
];
